version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - TZ=JST-9
      - PGTZ=JST-9
      - TERM=xterm
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    command: python manage.py runserver 0.0.0.0:13081
    volumes:
      - ./server:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    ports:
      - "13081:13081"