version: '3'
services:
  postgres:
    image: 'postgres:latest'
    command: localedef -i ja_JP -c -f UTF-8 -A /usr/share/locale/locale.alias ja_JP.utf8
    environment:
      - LANG=ja_JP.utf8
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    command: python manage.py runserver 0.0.0.0:13081
    volumes:
      - ./server:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    ports:
      - "13081:13081"