version: '3'
services:
  nginx:
    image: nginx:1.17
    container_name: django.nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./nginx/log:/var/log/nginx
    depends_on:
      - api
  postgres:
    image: 'postgres:latest'
    container_name: django.postgres
    environment:
      - TZ=JST-9
      - PGTZ=JST-9
      - TERM=xterm
  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    container_name: django.api
    command: uwsgi --ini /app/server/django.ini
    volumes:
      - ./server:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    ports:
      - "8001"
    depends_on:
      - postgres