version: '3'
services:
  nginx:
    image: nginx:1.17
    container_name: django.nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./nginx/log:/var/log/nginx
    depends_on:
      - api
  postgres:
    image: 'postgres:latest'
    build:
      dockerfile: Dockerfile
      context: ./postgres
    container_name: django.postgres
    # command: 'postgres -c config_file="/etc/postgresql.conf"'
    environment:
      - TZ=JST-9
      - PGTZ=JST-9
      - TERM=xterm
      # - POSTGRES_INITDB_ARGS="--encoding=UTF-8 --locale=ja_JP.UTF-8"
    volumes:
      # - database:/var/lib/postgresql/data
      - ./postgres/initdb:/docker-entrypoint-initdb.d
      # - ./postgres/postgresql.conf:/etc/postgresql.conf
    ports:
      - "5432:5432"
  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    container_name: django.api
    command: uwsgi --ini /app/django.ini
    # command: bash -c "python /app/manage.py makemigrations api --settings=server.settings_prd && python /app/manage.py migrate --fake --settings=server.settings_prd && uwsgi --ini /app/django.ini"
    volumes:
      - ./server:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    ports:
      - "8001:8001"
    depends_on:
      - postgres